### ISSUE TITLE
Add step to README about copying .env.example to .env

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-laravel#1]
I'm not very experienced with PHP, but I had some trouble setting up this project because the README didn't mention copying the `.env.example` file to `.env`.

Can you add a note about that?

I also had to run `php artisan key:generate` before the app would work, so maybe we need to add that to the README instructions also.

**Comment by jsantos17** [comment]
Yep. I'll add that. Thanks.

**Comment by jsantos17** [comment]
Addressed by 21d41f392f675148dd220db21a7d2960d092184c

**Comment by atbaker** [comment]
:+1:
