### ISSUE TITLE
Add a really simple response for the root URL

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-laravel#2]
The rails implementation has a really simple response when someone visits the `/` URL:

http://ivr-phone-tree-rails-2.herokuapp.com/

Can we add something like that to this app? Right now it 404s when someone tries to visit the home page, which could be confusing when a new developer is setting up the app for the first time.

**Comment by jsantos17** [comment]
Sure, I'll add that.

**Comment by jsantos17** [comment]
Addressed by 9f5f507fcd0d79568d911b2abd8fc596074d4503

**Comment by atbaker** [comment]
Beautiful - thanks!
