### ISSUE TITLE
Change "composer update" to "composer install" in the README

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-laravel#3]
I ran into errors following the README because it told me to run `composer update` instead of `composer install`. `composer update` kept erroring out for me.

I double-checked this with some other PHP experts at Twilio, and when a developer is cloning a repo for the first time, we should ask them to run `composer install` instead.

**Comment by jsantos17** [comment]
Yeah, my bad. It should have been `composer install`, not `composer update`.

**Comment by jsantos17** [comment]
Addressed by 21d41f392f675148dd220db21a7d2960d092184c

**Comment by atbaker** [comment]
:+1:
