### ISSUE TITLE
Remove bootstrap and any other UI dependencies from the project

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-laravel#4]
I spotted a few bootstrap dependencies in the project. Since this app doesn't have a UI, we should remove those to make this repo as simple as possible.

**Comment by jsantos17** [comment]
I'll remove the `package.json` file in the repo. It's unnecessary. I don't think there are any other references to bootstrap anywhere else.

**Comment by jsantos17** [comment]
Addressed by 21d41

**Comment by atbaker** [comment]
:+1:
