### ISSUE TITLE
Option #3 on in the showPlanetConnection errors for me

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-phone-tree-laravel#5]
Everything else in the IVR worked for me except this selection:

https://github.com/TwilioDevEd/ivr-phone-tree-laravel/blob/master/app/Http/Controllers/IvrController.php#L105

When I call +12013409912 I get the standard Twilio error message.

You can either fix the number you created for this tutorial, or use the ones from the Rails port:

https://github.com/TwilioDevEd/ivr-phone-tree-rails/blob/master/app/controllers/twilio_controller.rb#L47-L52

**Comment by jsantos17** [comment]
Oh right. I reused that number for the recording tutorial. I'll hardcode
the numbers from the Rails tutorial.

**Comment by jsantos17** [comment]
Addressed by 9f5f507fcd0d79568d911b2abd8fc596074d4503

**Comment by atbaker** [comment]
:+1: All the numbers work for me now.
